base_url = "https://sondnm.netlify.app"
title = "Blog Sơn Đặng"
description = "Notes about programming and stuffs"

compile_sass = true
highlight_code = true
build_search_index = true
theme = "lightspeed"

[extra]
author = "Sơn Đặng"

footer_links = [
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/rss.xml", name = "RSS"},
    {url = "https://github.com/sondnm", name = "Github"},
]

